# Generated by Django 3.1.4 on 2020-12-22 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sppt',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('nop', models.CharField(max_length=18)),
                ('tahun_pajak', models.IntegerField()),
                ('letak_objek_pajak', models.TextField()),
                ('id_wp', models.IntegerField()),
                ('op_bumi_njop', models.IntegerField()),
                ('op_bangunan_njop', models.IntegerField()),
                ('pbb_terhutang', models.IntegerField()),
                ('tgl_jatuh_tempo', models.DateField()),
                ('status', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pajak', models.IntegerField()),
                ('waktu_bayar', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Wajibpajak',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16)),
                ('nama', models.CharField(max_length=64)),
                ('jenis_kelamin', models.CharField(max_length=16)),
                ('tempat_lahir', models.CharField(max_length=64)),
                ('tanggal_lahir', models.DateField()),
                ('alamat', models.TextField()),
            ],
        ),
    ]
